Reset sources list in show-pr-change-note

diff --git a/.github/workflows/show-pr-change-note.yml b/.github/workflows/show-pr-change-note.yml
--- a/.github/workflows/show-pr-change-note.yml
+++ b/.github/workflows/show-pr-change-note.yml
@@ -9,13 +9,19 @@ jobs:
     name: Show Pull Request Change Note
     runs-on: ubuntu-latest
     steps:
-      - name: Enable Debug Logging
-        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
+      - name: Check current sources (debugging)
+        run: cat /etc/apt/sources.list || echo "sources.list not found"
+        
+      - name: Reset apt sources list
+        run: |
+          sudo tee /etc/apt/sources.list <<EOF
+          deb http://archive.ubuntu.com/ubuntu jammy main universe
+          deb http://archive.ubuntu.com/ubuntu jammy-updates main universe
+          deb http://security.ubuntu.com/ubuntu jammy-security main universe
+          EOF
 
       - name: Update apt cache
-        run: |
-          echo "Updating apt cache..."
-          sudo apt-get update
+        run: sudo apt-get update
 
       - name: Use The Release Notes Manager Action
         uses: Ahmed-Khaled-dev/release-notes-manager@v1
